development:
  adapter: postgresql
  database: flipper_baby_development
  username: developer
  password: isotope_bang
  host: localhost
  encoding: UTF8

test: &test
  adapter: postgresql
  database: flipper_baby_test
  username: developer
  password: isotope_bang
  host: localhost
  encoding: UTF8

production:
  adapter: postgresql
  database: flipper_baby_production
  username: developer
  password: isotope_bang
  host: localhost
  encoding: UTF8

cucumber:
  <<: *test

