require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GalleryPiecesController do

  # This should return the minimal set of attributes required to create a valid
  # GalleryPiece. As you add validations to GalleryPiece, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GalleryPiecesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all gallery_pieces as @gallery_pieces" do
      gallery_piece = GalleryPiece.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gallery_pieces).should eq([gallery_piece])
    end
  end

  describe "GET show" do
    it "assigns the requested gallery_piece as @gallery_piece" do
      gallery_piece = GalleryPiece.create! valid_attributes
      get :show, {:id => gallery_piece.to_param}, valid_session
      assigns(:gallery_piece).should eq(gallery_piece)
    end
  end

  describe "GET new" do
    it "assigns a new gallery_piece as @gallery_piece" do
      get :new, {}, valid_session
      assigns(:gallery_piece).should be_a_new(GalleryPiece)
    end
  end

  describe "GET edit" do
    it "assigns the requested gallery_piece as @gallery_piece" do
      gallery_piece = GalleryPiece.create! valid_attributes
      get :edit, {:id => gallery_piece.to_param}, valid_session
      assigns(:gallery_piece).should eq(gallery_piece)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GalleryPiece" do
        expect {
          post :create, {:gallery_piece => valid_attributes}, valid_session
        }.to change(GalleryPiece, :count).by(1)
      end

      it "assigns a newly created gallery_piece as @gallery_piece" do
        post :create, {:gallery_piece => valid_attributes}, valid_session
        assigns(:gallery_piece).should be_a(GalleryPiece)
        assigns(:gallery_piece).should be_persisted
      end

      it "redirects to the created gallery_piece" do
        post :create, {:gallery_piece => valid_attributes}, valid_session
        response.should redirect_to(GalleryPiece.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gallery_piece as @gallery_piece" do
        # Trigger the behavior that occurs when invalid params are submitted
        GalleryPiece.any_instance.stub(:save).and_return(false)
        post :create, {:gallery_piece => { "title" => "invalid value" }}, valid_session
        assigns(:gallery_piece).should be_a_new(GalleryPiece)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GalleryPiece.any_instance.stub(:save).and_return(false)
        post :create, {:gallery_piece => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gallery_piece" do
        gallery_piece = GalleryPiece.create! valid_attributes
        # Assuming there are no other gallery_pieces in the database, this
        # specifies that the GalleryPiece created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GalleryPiece.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => gallery_piece.to_param, :gallery_piece => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested gallery_piece as @gallery_piece" do
        gallery_piece = GalleryPiece.create! valid_attributes
        put :update, {:id => gallery_piece.to_param, :gallery_piece => valid_attributes}, valid_session
        assigns(:gallery_piece).should eq(gallery_piece)
      end

      it "redirects to the gallery_piece" do
        gallery_piece = GalleryPiece.create! valid_attributes
        put :update, {:id => gallery_piece.to_param, :gallery_piece => valid_attributes}, valid_session
        response.should redirect_to(gallery_piece)
      end
    end

    describe "with invalid params" do
      it "assigns the gallery_piece as @gallery_piece" do
        gallery_piece = GalleryPiece.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GalleryPiece.any_instance.stub(:save).and_return(false)
        put :update, {:id => gallery_piece.to_param, :gallery_piece => { "title" => "invalid value" }}, valid_session
        assigns(:gallery_piece).should eq(gallery_piece)
      end

      it "re-renders the 'edit' template" do
        gallery_piece = GalleryPiece.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GalleryPiece.any_instance.stub(:save).and_return(false)
        put :update, {:id => gallery_piece.to_param, :gallery_piece => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gallery_piece" do
      gallery_piece = GalleryPiece.create! valid_attributes
      expect {
        delete :destroy, {:id => gallery_piece.to_param}, valid_session
      }.to change(GalleryPiece, :count).by(-1)
    end

    it "redirects to the gallery_pieces list" do
      gallery_piece = GalleryPiece.create! valid_attributes
      delete :destroy, {:id => gallery_piece.to_param}, valid_session
      response.should redirect_to(gallery_pieces_url)
    end
  end

end
